dist: xenial
language: python
python:
    -  "3.7"

before_install:
    - sudo apt-get install libhdf5-serial-dev

install:
    # Install Anaconda
    - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
            wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
        else
            wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
        fi
    - bash miniconda.sh -b -p $HOME/miniconda
    - rm miniconda.sh
    - export PATH="$HOME/miniconda/bin:$PATH"
    - hash -r
    - conda config --set always_yes yes --set changeps1 no
    - conda update -q conda
    - conda env create -f build.yml
    - source activate stats_can_build

script:
    - pytest -v --cov=./stats_can

after_success:
    - codecov -t cf1d3cea-dbb3-4e40-9060-71791599cac4
    - test $TRAVIS_BRANCH = "master" && conda install conda-build && conda install anaconda-client && bash conda_upload.sh
