name: stats_can_build
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - pandas
  - numpy
  - requests
  - h5py
  - tqdm
  - pytables
  - pytest
  - pytest-cov
  - codecov
