name: PyPi
on:
  push:
    branches:
      - master
jobs:
  pypi:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
      with:
        python-version: '3.8'
        architecture: x64
    - run: pip install poetry==1.0.10
    - run: poetry build
    - uses: pypa/gh-action-pypi-publish@v1.0.0a0
      with:
        user: __token__
        password: ${{ secrets.PYPI_TOKEN }}
        repository_url: https://pypi.org/legacy/
